substitutions:

  device_name: "rain"
  friendly_name: Rain
  board_type: esp32dev
  flash_size: 4MB
  framework: esp-idf
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
esp32:
  board: ${board_type}
  framework:
    type: ${framework}
network:
  enable_ipv6: True
  min_ipv6_addr_count: 2
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
    
captive_portal:
logger:
api:
ota:
  platform: esphome
binary_sensor:
- platform: gpio
  pin:
    number: 36
    mode:
      input: true
      pullup: true
      output: false
      open_drain: false
      pulldown: false
    inverted: false
  name: smutregn
  device_class: door
  filters:
  - delayed_on: 10ms
  disabled_by_default: false
  
text_sensor:
  - platform: wifi_info
    ip_address:
     name: IP Address
     icon: mdi:ip-network
    ssid:
      name: SSID
      icon: mdi:access-point-network
    mac_address:
      name: Mac Address
      icon: mdi:lan

